### ISSUE TITLE
What's the different to emilsjolander's IntentBuilder?

### ISSUE THREAD

**Issue by bu2zhouzhu** [Trikke/intentbuilder#1]
What's the different to [emilsjolander's IntentBuilder](https://github.com/emilsjolander/IntentBuilder)?
Can you list all advantages?

**Comment by Trikke** [comment]
Mostly the fact that you can add flags, data, and more to the Intent Builder itself. Which couldn't be done with emilsjolander's lib. I also liked to have a "shortcut" class to all the intents that are available.

His lib didn't seem to be updated in a year, and any request weren't look at, so i decided to create one for my own need. Any feature request or idea's are of course welcome.

**Comment by Trikke** [comment]
Oh, and now it works on broadcastreceivers as well!

**Comment by bu2zhouzhu** [comment]
Good :+1:
