### ISSUE TITLE
What about default values? 

### ISSUE THREAD

**Issue by Rainer-Lang** [Trikke/intentbuilder#3]
Do I have to use/set all @NonNull attributes in builder even when I set a default value in activity?

**Comment by Trikke** [comment]
No, if you don't set a value in the builder, the field will not be overwritten on injection. "Optional" means that the Extra is not a requirement to start the Activity. So you can add a value in the builder, if your use case needs it.

An example:
(i've just updated to v1.1.0, so this example uses the new annotation)

``` java
@BuildIntent public class DetailActivity extends AppCompatActivity {
    @ExtraOptional String optionalString = "activity";

    @Override public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        DetailActivityIntent.inject(getIntent(), this);
        setContentView(R.layout.activity_detail);

        // use extras
    }
}
```

If you don't set the optional value in the builder, the value will still be **"activity"**

``` java
Flow.gotoDetailActivity().launch(MainActivity.this);
```

If you set the optional value in the builder, the value will be **"builder value"**

``` java
Flow.gotoDetailActivity().optionalString("builder value").launch(MainActivity.this);
```

**Comment by Rainer-Lang** [comment]
@Trikke Thank you very much.
